### ISSUE TITLE
Bandit Invisibility

### ISSUE THREAD

**Issue by shadowshrig** [Fesmaster/QuestTest2#83]
Bandits are invisible under water (both river water and regular water)

**Comment by Fesmaster** [comment]
Limitation of the Minetest Engine. Both water and bandits are considered "translucent", so only the front one is rendered.
Bandits are "translucent" due to armor.

While we can potentially make a task for investigating an armor system that does not require the entities to be "translucent", that would be a dedicated issue, and may or may not be successful.
